### PR TITLE
Feature/Check-particles-in-box

### LINKED ISSUE #582: Raise error when particle positions are outside of box
**Describe the bug**
Analysis returns incorrect results when points lie outside of a freud `Box`. I ran into this issue when cropping my simulation box to calculate Voronoi tesselation. When the new box size is definied incorrectly, the Voronoi diagram produced was not space filling.

Freud should raise an error when users try to create systems when points lie outside of the sytsem box.

**To Reproduce**
A) Minimal example to reproduce error:
```python
import matplotlib.pyplot as plt
import freud
import gsd.hoomd

# Open file
t = gsd.hoomd.open('ideal_tiling.gsd', mode='rb')
pos = np.copy(t[0].particles.position)

# Crop positions
pos = pos[abs(pos[:, 0]) < 20]
pos = pos[abs(pos[:, 1]) < 20]

# Crop box
box = freud.Box.square(L=20.0)

# Voronoi calculations and plotting
voro = freud.locality.Voronoi.compute((box, sys))
plt.figure()
ax = plt.gca()
ax.scatter(pos[:, 0], pos[:, 1], s=2, c='black')
voro.plot(ax=ax)
plt.show()
```

B) Minimal example to reproduce correct plot:
```python
import matplotlib.pyplot as plt
import freud
import gsd.hoomd

# Open file
t = gsd.hoomd.open('ideal_tiling.gsd', mode='rb')
pos = np.copy(t[0].particles.position)

# Crop positions
pos = pos[abs(pos[:, 0]) < 20]
pos = pos[abs(pos[:, 1]) < 20]

# Crop box
box = freud.Box.square(L=40.0)

# Voronoi calculations and plotting
voro = freud.locality.Voronoi.compute((box, sys))
plt.figure()
ax = plt.gca()
ax.scatter(pos[:, 0], pos[:, 1], s=2, c='black')
voro.plot(ax=ax)
plt.show()
```
**Error output**
A) Wrong Voronoi plot
image

B) Expected Voronoi plot
image

File used to generate these plots provided here: [ideal_tiling.zip](https://github.com/glotzerlab/freud/files/4182797/ideal_tiling.zip)

**System configuration (please complete the following information):**
 - OS: Linux Mint and MacOS
 - Version of Python: 3.8.1
 - Version of freud: 2.1.0

### PR DESCRIPTION
**Pull request by klywang**
Add option to check if provided points and query points are in the box using `freud.box.Box.contains`.

## Description

When check is turned on, `freud` will raise a `ValueError` if any points or query points are outside of the provided box.

## Motivation and Context

Resolves: #582 

## How Has This Been Tested?

Tests are in progress.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation improvement (updates to user guides, docstrings, or developer docs)

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation (if relevant).
- [ ] I have added tests that cover my changes (if relevant).
- [ ] All new and existing tests passed.
- [ ] I have updated the [credits](https://github.com/glotzerlab/freud/blob/master/doc/source/reference/credits.rst).
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

### CODE REVIEW

**Comment by klywang** [comment]
For some features, it seems that turning on the check by default will result in a major performance hit, while other suffer little to no changes in performance (shown in figures below). To prevent slowdown of CI tests, I temporarily set the default as no checking (with the exception of tests for this function, which I have yet to commit). 

Do we still want to add this check? If so, do we want to turn it on or off by default? I know this has been asked before by @vyasr offline, but I'm curious what @glotzerlab/freud-developers think, given data on how this check affects runtime.  If decide to include this, and want this to be the default behavior without too much sacrifice to performance, we could turn off checks for ``freud.density.Correlation.Function`` by default, and on for all others. I think this would be fine if we provide a clear, hard to miss note that this was turned off for performance reasons. We should also include a note in the docs for all modules that perform this check that tells users that turning off the check will help the function run faster.

Percent change in runtime with particle checking on vs with particle checking off. 
Linear plot:
percent_change

Log plot:
percent_change_log


I have also provided a zip of plots with run times, with and without in box check.
Runtime vs. number of particles 
Run with 8 threads. For really slow modules (is the right word?) (ie. ``CorrelationFunction``), the number of query points were reduced so I could run all of these. 
[time_plots.zip](https://github.com/glotzerlab/freud/files/5561942/time_plots.zip)

**Comment by tommy-waltmann** [comment]
I think this check should be added in all compute classes which will give incorrect results if there are particles are outside of the box.

In deciding whether to turn it on or off by default, we should consider whether the majority of use cases have `points`/`query_points` which are already guaranteed to be inside the box. If the user is doing some simulation analysis, the points and query points will likely be guaranteed to be inside the box already, and I think in those cases it would be annoying to constantly have to turn the check off manually. There are obviously cases where this won't be true (such as @klywang's original case motivating this feature), but I think for the majority of cases the check may be unnecessary.

I would love to have some more discussion on this.

**Comment by bdice** [comment]
@tommy-waltmann I chatted with @klywang (before your comment) and we decided we would gather some information on related questions. e.g. What currently happens if particles are outside the box for various methods? Are neighbors found correctly? We're planning to bring this up in an upcoming developer meeting and solicit some input there.

**Comment by klywang** [comment]
Here is how `LinkCell` and `AABBQuery` handle out-of-box points in a 2D box. 

Solid circles show original out-of-box positions. Dashed circles show position of points wrapped with `freud.box.Box.wrap`:

AABBQuery2
LinkCell2

For a square box:
AABBQuery1
LinkCell1

Points that are very far out of the box (ie. 1 or 2 full images) were cropped out. ``AABBQuery`` shows different behavior when out-of-box points are query points and when they are reference points. ``LinkCell`` behaves the same, regardless of if the out-of-box points are query points or reference points

@tommy-waltmann I will bring up these results during our Dev meeting next week, but I tagged you in case you wanted to take a look beforehand. I only ran the analysis on ``AABBQuery`` and ``LinkCell``, since the neighbor-based analysis (except voronoi calculations) use these ``locality`` modules in their calculations (@bdice please correct me if I'm wrong/missed anything that needed testing).

**Comment by bdice** [comment]
@klywang This is awesome, thanks so much for testing this. 👍 I suspected there might be differences between LinkCell and AABBQuery. I look forward to discussing at the next dev meeting.

Could you please share the code that generated this so I can experiment a bit more? You can use a Gist to paste/upload the code or notebook (it’s probably too long for pasting inline in a comment). https://gist.github.com/

**Comment by klywang** [comment]
@bdice Here is a link to the code [[x](https://gist.github.com/klywang/112e824070ccef6208ea17299dd860b1)]. The code structure is a bit all over the place. Let me know if you have any questions.

**Comment by tommy-waltmann** [comment]
I don't quite understand what I'm looking at with these figures. There appear to be 4 kinds of circles: filled-in circles, open circles, open circles with a dashed outline, and open circles with a triangle in the middle of them. Can you clarify what exactly the different kind of circles mean? You mentioned 2 of the kinds already, but I still don't understand ...

EDIT: There are also partially filled in circles, some of which have dashed outlines, and some of which do not. Plz clarify

**Comment by klywang** [comment]
@tommy-waltmann 
> I don't quite understand what I'm looking at with these figures. There appear to be 4 kinds of circles: filled-in circles, open circles, open circles with a dashed outline, and open circles with a triangle in the middle of them. Can you clarify what exactly the different kind of circles mean? You mentioned 2 of the kinds already, but I still don't understand ...

Summary of plot legends:

- **Triangle points** are points that were places outside of the box. Circles were used to make these points easier to spot.
- Circles with **solid lines** are locations of out-of-box points.
- Circles with **dashed lines** are locations of the out-of-box points wrapped using `freud.box.Box.wrap`.
- The **radius of the circles** corresponds to the query arguments (`{'mode': 'ball', 'r_max': 3.0}`).
- **Black points** are in box points that were not recognized as neighbors to any out-of-box points according to the `NeighborList` returned from respective `locality` modules.
- **Colored points** match the color of the out-of-box point (circle outline color)



> EDIT: There are also partially filled in circles, some of which have dashed outlines, and some of which do not. Plz clarify

Circles that look completely filled in are regions where all the particles within `r_max` were recognized as neighbors. Circles that are partially filled or completely empty are due to errors in the neighbor search. 
Solid patches of points outside of circles are due to periodic BCs (ie edge or corner cases).

**Comment by klywang** [comment]
From our discussion offline, we decided that the performance hit from this check was too large. It will not be implemented. Instead, we will update the documentation to acknowledge undefined behavior when points are out-of-box. We will also provide code snippet(s) to show users how they can add their own particle check.

**Pull request closed without merging**
