### PR TITLE
Use ManagedArray in ParticleBuffer

### PR DESCRIPTION
**Pull request by bdice**
## Description
Switched ParticleBuffer to use ManagedArrays.

## Motivation and Context
More ManagedArray conversions.

## How Has This Been Tested?
Existing tests pass.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have updated the documentation (if relevant).
- [x] I have added tests that cover my changes (if relevant).
- [x] All new and existing tests passed.
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

### CODE REVIEW

**Comment by bdice** [comment]
@vyasr Following up on our offline discussion about whether this should be a ManagedArray or not, I prefer to keep it as-is in this PR and use a ManagedArray. If I recall correctly, it's not straightforward to convert a `vector<vec3<float>>` to an `(N, 3)` NumPy array without some memory view magic (potentially involving some raw pointer casting), since it involves `vec3`s. That would be easy if it were a vector of primitive types, but I would prefer to avoid retaining memory view logic in freud's Cython layer if we can avoid it.

**Comment by vyasr** [comment]
Maybe it wasn't clear in our offline discussion, what I was proposing was just returning a copy. There's no reason not to if we're already forced to copy internally to generate the ManagedArray. So there wouldn't be any memoryviews, we'd just return a copy of the vector and use:

```
        particles = self.thisptr.getBufferParticles()
        return np.asarray([[p.x, p.y, p.z] for p in particles])
```

**Comment by vyasr** [comment]
I actually already implemented the change and just saw this comment when I came back here. I'm going to push, but we can revert my commit if we decide to stick with ManagedArray here.

**Comment by bdice** [comment]
@vyasr Tests are failing for Voronoi because of a lack of memory contiguity in the input array of buffer particles. Shall we treat this as an error for ParticleBuffer (changing from contiguous to non-contiguous arrays) or the Voronoi class (not ensuring its data is contiguous) or both? Should we call `freud.common.convert_array` on the output?

**Comment by vyasr** [comment]
> @vyasr Tests are failing for Voronoi because of a lack of memory contiguity in the input array of buffer particles. Shall we treat this as an error for ParticleBuffer (changing from contiguous to non-contiguous arrays) or the Voronoi class (not ensuring its data is contiguous) or both? Should we call `freud.common.convert_array` on the output?

From a quick glance, it seems like the most natural place to fix this is in `_qhull_compute`. Users of `ParticleBuffer` may not care about contiguity, but `Voronoi` does, so `Voronoi` should fix it. Does that seem reasonable?

Also, feel free to resolve the other discussion as you see fit.

**Review by vyasr — APPROVED** [review]

**Pull request merged**
