### PR TITLE
Use voro++ for Voronoi computations.

### PR DESCRIPTION
**Pull request by bdice**
## Description
This PR adds the [voro++](http://math.lbl.gov/voro++/) library written by Chris Rycroft (@chr1shr) to freud. This will replace the existing Voronoi methods, which used less sophisticated algorithms and were quite slow.

## Motivation and Context
Issue #305 describes challenges with Voronoi performance -- this continues to be a bottleneck for my current analyses, so I found it worthwhile to rewrite this entire feature using voro++.

## How Has This Been Tested?
I have adapted existing Voronoi tests, which work as expected in both 2D and 3D systems. Some changes (like reordering of vertices in a Voronoi cell) are expected, so I added functions to sort the vertices in a deterministic way for the purpose of testing. Currently, this new approach is about 32x faster for a system of 5000 random points in a cubic box of side length 10.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds or improves functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have updated the documentation (if relevant).
- [x] I have added tests that cover my changes (if relevant).
- [x] All new and existing tests passed.
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

### CODE REVIEW

**Comment by bdice** [comment]
To-Do:
- [x] Expand test suite
- [x] Replace previous Voronoi code (rename `freud.locality._VoroPlusPlus` to `freud.locality.Voronoi`)
- [x] Decide if other cell properties should be added (since they're almost free)
  - Not for now.
- [x] Revise API
- [x] Remove unneeded C++ code (debugging, extra computed properties, etc.)
- [x] Update documentation

**Comment by bdice** [comment]
@vyasr Currently this is using a direct copy-paste of the source tarball. I think this is the definitive repo source: https://repo.or.cz/voro++.git We should probably change this into a git submodule -- should we add it directly, or as a mirror via the glotzerlab organization? We have Eigen mirrored, and we control all other submodules.

**Comment by vyasr** [comment]
Even that git repo looks like a mirror. The "active" repo (last commit was 2017-09-29, so almost 2 years ago) is the [Subversion repository](https://code.lbl.gov/scm/?group_id=108). Of course, maintaining an svn repository inside a git repository would be a huge pain, and I wouldn't advocate that. I think the relevant question is whether you think any further updates to the code are forthcoming, and if so, whether they will get into the git repository.

I don't think that we should maintain our own mirror. It introduces unnecessary maintenance overhead that I don't think is terribly helpful, and I believe that we're moving away from that with Eigen too (IIRC Josh plans to remove that mirror when HOOMD gets the 3.0 version bump and stops using submodules). So I'd say that copying in the code is actually not the worst option, unless you think that future updates will make it into the git repository, in which case a submodule would work fine.

**Comment by chr1shr** [comment]
I am actually planning to convert the old Subversion repository into a Git repo in the coming month. I recently got a grant to further Voro++ development and this is the first step to doing that. Hence, if you want to incorporate the library as a submodule, that could work.

There are a number of developments that I've already done, or plan to incorporate as part of the grant: (A) 2D computations, (B) more reliable 3D computations, (C) multi-threading, (D) parallelization via domain decomposition. A & B are already mainly done, C is ongoing, and D is future work.

**Comment by bdice** [comment]
@chr1shr Wonderful to hear! Glad I tagged you. :) I implemented fake 2D computations by just putting the points in the z=0 plane and using the top surface of a box with height 1. Please do let us know when you make a git repo!

In particular with multithreading, we use Intel Threading Building Blocks in our code. I think it would work immediately for us if I could get the loop object over all particles in the container to be easier to index, so that blocks of cells could be assigned to each thread.

**Comment by bdice** [comment]
I'm closing this PR so that I can use its final set of C++/Cython files but re-do the branch with a git submodule. I was not successful in rebasing the original "source copy" commit by replacing it with a git submodule addition.

**Pull request closed without merging**
