### PR TITLE
Use interpolation to improve stability of bins.

### PR DESCRIPTION
**Pull request by bdice**
## Description
A user reported numerical issues with bin edges/centers in RDF. I edited the calculation of bin edges in `Histogram.h` to make the calculation more stable.

## Motivation and Context
Improves numerical stability of all histogram classes.

## How Has This Been Tested?
[freud_54a717c.txt](https://github.com/glotzerlab/freud/files/4529470/freud_54a717c.txt)

[freud_v220.txt](https://github.com/glotzerlab/freud/files/4529471/freud_v220.txt)
```python
# comparison.py
import freud
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

rdf = freud.density.RDF(bins=500, r_max=50)

freud_54a717c = np.genfromtxt('freud_54a717c.txt')
freud_v220 = np.genfromtxt('freud_v220.txt')

expected_bins = np.histogram_bin_edges(np.array([0], dtype=np.float32), bins=500, range=[0, 50])

with plt.style.context('bmh'):
    plt.xlabel('Bin edge')
    plt.ylabel('Deviation from expected')
    plt.plot(freud_v220 - expected_bins, label='freud v2.2.0')
    plt.plot(freud_54a717c - expected_bins, label='freud 54a717c')
    plt.plot(rdf.bin_edges - expected_bins, label='Current build')
    plt.legend()
    plt.savefig('comparison.png', bbox_inches='tight')
    plt.close()
```
Files attached.

## Screenshots
comparison

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation (if relevant).
- [x] I have added tests that cover my changes (if relevant).
- [x] All new and existing tests passed.
- [x] I have updated the [credits](https://github.com/glotzerlab/freud/blob/master/doc/source/reference/credits.rst).
- [x] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

### CODE REVIEW

**Comment by vyasr** [comment]
@bdice while you're fixing the tests, could you change the linear interpolation to instead just use multiplication by `m_dr` (i.e. do `m_bin_edges[i] = min + i*m_inverse_bin_width`)? That will also avoid the accumulation of error while also ensuring better agreement with the binning procedure.

**Comment by bdice** [comment]
@vyasr If I use the formula you suggested, the tests do not need to be edited. The errors are still small (the "Current build" uses `min + i * m_bin_width`):
comparison

**Comment by vyasr** [comment]
OK awesome that seems like the best of both worlds then.

**Review by vyasr — APPROVED** [review]
LGTM

**Pull request merged**
