### PR TITLE
Fix/issue 559

### LINKED ISSUE #559: Querying link 404s
**Describe the bug**
On this page of the docs:
https://freud.readthedocs.io/en/stable/modules/locality.html#freud.locality.LinkCell.query
The link to the quarry API 404s:
https://freud.readthedocs.io/en/stable/querying.html
The link should be:
https://freud.readthedocs.io/en/stable/topics/querying.html

I will submit a PR to fix this.

### PR DESCRIPTION
**Pull request by mikemhenry**
## Description
Fixes #559  where the urls would point either to the `next` branch or would not have the `topic` subsection.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have updated the documentation (if relevant).
- [x] I have added tests that cover my changes (if relevant).
- [x] All new and existing tests passed.
- [x] I have updated the [credits](https://github.com/glotzerlab/freud/blob/master/doc/source/reference/credits.rst).
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

### CODE REVIEW

**Review by bdice — CHANGES_REQUESTED** [review]
Looks good overall. Two requests:

1. I think there's one link we missed, in `box.pyx:36`. Fix: "https://freud.readthedocs.io/en/stable/tutorial/periodic.html" to "https://freud.readthedocs.io/en/stable/gettingstarted/tutorial/periodic.html"

2. Can you revert your changes to the generated CPP files? We only update those during releases. Apologies, this probably isn't marked in our [dev guide](https://freud.readthedocs.io/en/stable/reference/development.html) (I didn't see it explicitly mentioned during a quick glance.)

**Comment by mikemhenry** [comment]
Not sure how to make the url any shorter to make the style checker happy, is there a pragma I can add so it skips the check for that doc string?

**Comment by bdice** [comment]
@mikemhenry End the docstring with a directive to ignore the line length. Also wrap the other words after the URL ends. :)
```python
"""Some docstring stuff
bla bla bla
"""   # noqa: E501
```

**Review by bdice — APPROVED** [review]
LGTM, thanks so much @mikemhenry!

**Comment by bdice** [comment]
@mikemhenry Sorry, one more thing -- add this to your name in the credits. No changelog line is needed. Then I'll merge it.

**Pull request merged**
