### PR TITLE
Fix box docs

### PR DESCRIPTION
**Pull request by bdice**
## Description
@ramanishsingh caught an error in the box class documentation: masses are an array of shape `(N,)`, not `(N, 3)`.

I also added return types to a few methods that were missing them.

This PR also fixes a minor nitpick that has always confused me. Raw strings can be written with `R"` or `r"`, but I am used to seeing the lowercase form everywhere except in freud. For clarity (and to use the more common format), I flipped them to use the lowercase form.

## Motivation and Context
Fixes docs. No changelog line needed.

## How Has This Been Tested?
ReadTheDocs should render correctly.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation improvement (updates to user guides, docstrings, or developer docs)

## Checklist:
- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have updated the documentation (if relevant).
- [x] I have added tests that cover my changes (if relevant).
- [x] All new and existing tests passed.
- [ ] I have updated the [credits](https://github.com/glotzerlab/freud/blob/master/doc/source/reference/credits.rst).
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

### CODE REVIEW

**Review by j-proc — COMMENTED** [review]
Looks fine to me, the (N,3) shape is obviously nonsensical and a missed clean up from copy/paste for the documentation structure.

@bdice as for the r/R issue. It's my preference as well, just because the way it reads is more clearly a formatting syntax and not the start of a line you should actually read. However, I think if you're going to make this change, we need to do something to make its consistency enforced. I'm not sure if that means making it explicit in some documentation or if it could be added to pre-commit. You're more of a pre-commit expert to know if it's possible.

**Comment by bdice** [comment]
> @bdice as for the r/R issue. It's my preference as well, just because the way it reads is more clearly a formatting syntax and not the start of a line you should actually read. However, I think if you're going to make this change, we need to do something to make its consistency enforced. I'm not sure if that means making it explicit in some documentation or if it could be added to pre-commit. You're more of a pre-commit expert to know if it's possible.

I'm not familiar with a way to enforce this, unfortunately. Most of the code in freud is written by copy-paste, so I suspect this won't require too much ongoing maintenance. There is one test with a random failure -- we can ignore it for now, this happens on rare occasions. We could increase the tolerance for that test at some point but it doesn't fit in this PR's scope. @j-proc Please approve once you're ready. 👍

**Comment by itsagoodbrain** [comment]
> I'm not familiar with a way to enforce this, unfortunately. Most of the code in freud is written by copy-paste, so I suspect this won't require too much ongoing maintenance.

That's a good point. This is somewhat unrelated to the main fix which is needed. Approving

**Review by j-proc — APPROVED** [review]
That's a good point. It's unrelated to the main issue anyways. Approving.

**Pull request merged**
