### PR TITLE
[WIP] Parallelize Steinhardt Ql calculation.

### PR DESCRIPTION
**Pull request by bdice**
This PR parallelizes the computation of Steinhardt Ql order parameters and other variants present in `freud`.

I opened this PR as a work-in-progress so that I could track the performance.

## To-Do
- [ ] Refactor variants of `LocalQl.compute` to use a shared parallel compute method
  - [ ] `LocalQl.computeAve`
  - [ ] `LocalQl.computeNorm`
  - [ ] `LocalQl.computeAveNorm`
  - [ ] `LocalWl.compute`
  - [ ] `LocalWl.computeAve`
  - [ ] `LocalWl.computeNorm`
  - [ ] `LocalWl.computeAveNorm`
  - [ ] Review `SolLiq` internals, refactor appropriately
- [ ] Create regression tests

## Benchmarks
Input data: fcc structure, 20x20x20 unit cells (=32k particles) with noise=0.1
System: 16-core Intel Xeon Silver 4110 @ 2.10 GHz.
- Q6: 0.95 seconds before (commit 8bb083f), 0.15 seconds with parallelism (commit e901a97) (6.3x speedup over 16 cores)

### CODE REVIEW

**Comment by vyasr** [comment]
Can we follow the convention that when [WIP] PRs are ready for review we rename them and remove that tag?

**Comment by bdice** [comment]
> 
> 
> Can we follow the convention that when [WIP] PRs are ready for review we rename them and remove that tag?

Since the creation of this PR, GitHub has added a feature for [Draft Pull Requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/) - this PR cannot be converted to a draft PR, but that should be our standard going forward.

**Comment by b-butler** [comment]
Sorry, it seems when my computer froze, it reset multiple files without me realizing it. That is why the test broke.

**Comment by bdice** [comment]
@vyasr @b-butler I would like to merge this in its pre-hackathon state f36de0c, so that we can immediately see the benefits of some parallel Ql computations without having to wait for the rest of the refactoring that occurred after that point. Thoughts?

**Comment by vyasr** [comment]
@bdice this is superseded by #242 once it's merged, right?

**Comment by bdice** [comment]
> 
> 
> @bdice this is superseded by #242 once it's merged, right?

Yes, I think so. The part I really wanted to get merged was in #247.

**Pull request closed without merging**
