### PR TITLE
Changed return value in documentation

### LINKED ISSUE #763: Wrong return value in docs for NeighborQuery.plot()
**Describe the bug**
The [docs for `NeighborQuery.plot()`](https://freud.readthedocs.io/en/stable/modules/locality.html#freud.locality.NeighborQuery.plot) show that just the `matplotlib.axes.Axes` is returned, but the entire `PathCollection` (i.e., the set of points in the scatter plot) is also returned.

### PR DESCRIPTION
**Pull request by marxd1**
Changed the documentation in locality.pyx to show the true return value of plot in NeighborQuery class. 

## Description
Changed the documentation in locality.pyx to show the true return value of plot in NeighborQuery class. 

## Motivation and Context

Resolves: #763 

## How Has This Been Tested?
Will write tests if needed later. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation improvement (updates to user guides, docstrings, or developer docs)

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation (if relevant).
- [ ] I have added tests that cover my changes (if relevant).
- [ ] All new and existing tests passed.
- [ ] I have updated the [credits](https://github.com/glotzerlab/freud/blob/master/doc/source/reference/credits.rst).
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

### CODE REVIEW

**Comment by tommy-waltmann** [comment]
Since the `freud.plot.system_plot` function returns a tuple containing both the `matplotlib.axes.Axes` and the `matplotlib.collections.PathCollection` object, let's document that both are being returned here. Since the above function is only called in one place, that should be all there is to do on this PR.

**Comment by marxd1** [comment]
I have added that both are returned here. There is an additional comment that I left with the matplotlib.axes.Axes, however I did not add one to the matplotlib.collections.PathCollection.

**Comment by tommy-waltmann** [comment]
For the description of the `PathCollection` object, you could just say the point data for the plot. We don't need to be overly specific with this description. After you've added that, you can upgrade this to a full PR and get reviews from other glotzerlab members.

**Comment by marxd1** [comment]
I have added that note and will now close this draft pull request and turn it into a real pull request.

**Comment by vyasr** [comment]
@marxd1 did you mean to convert this from a draft PR into one ready for review?

**Comment by marxd1** [comment]
Yes @vyasr, this is my first time doing this so I accidentally clicked the wrong button.

**Comment by bdice** [comment]
We will need to tweak the formatting a bit here. Sphinx doesn’t seem to know that these are both part of a single returned tuple.
CC82F553-B00A-4B79-B0F5-9E67C98F3054

Here is an example of a tuple return:
https://github.com/glotzerlab/freud/blob/5e16b45ffed9b9dd39e3c719a5f032f6d066d0c1/freud/data.py#L212-L214

**Comment by tommy-waltmann** [comment]
Another note on contributing to freud: Because this is an open-source project, we like to give credit to those that contribute. @marxd1 in the file `doc/source/reference/credits.rst`, you can add your name to the list of contributors and write a sentence about how you've contributed to freud before this PR gets merged.

**Review by vyasr — APPROVED** [review]

**Pull request merged**
